# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param general.maxThreads 8
set_param chipscope.maxJobs 3
create_project -in_memory -part xc7a35ticsg324-1L

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/KachiCodeRsp/customriscv/cv32e40x/vivado_project/cv32e40x_project.cache/wt [current_project]
set_property parent.project_path D:/KachiCodeRsp/customriscv/cv32e40x/vivado_project/cv32e40x_project.xpr [current_project]
set_property default_lib work [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/KachiCodeRsp/customriscv/cv32e40x/vivado_project/cv32e40x_project.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -sv {
  D:/KachiCodeRsp/customriscv/cv32e40x/rtl/include/cv32e40x_pkg.sv
  D:/KachiCodeRsp/customriscv/cv32e40x/rtl/cv32e40x_a_decoder.sv
  D:/KachiCodeRsp/customriscv/cv32e40x/rtl/cv32e40x_align_check.sv
  D:/KachiCodeRsp/customriscv/cv32e40x/rtl/cv32e40x_alignment_buffer.sv
  D:/KachiCodeRsp/customriscv/cv32e40x/rtl/cv32e40x_alu.sv
  D:/KachiCodeRsp/customriscv/cv32e40x/rtl/cv32e40x_alu_b_cpop.sv
  D:/KachiCodeRsp/customriscv/cv32e40x/rtl/cv32e40x_b_decoder.sv
  D:/KachiCodeRsp/customriscv/cv32e40x/rtl/cv32e40x_clic_int_controller.sv
  D:/KachiCodeRsp/customriscv/cv32e40x/rtl/cv32e40x_clock_gate_fpga.sv
  D:/KachiCodeRsp/customriscv/cv32e40x/rtl/cv32e40x_compressed_decoder.sv
  D:/KachiCodeRsp/customriscv/cv32e40x/rtl/cv32e40x_controller.sv
  D:/KachiCodeRsp/customriscv/cv32e40x/rtl/cv32e40x_controller_bypass.sv
  D:/KachiCodeRsp/customriscv/cv32e40x/rtl/cv32e40x_controller_fsm.sv
  D:/KachiCodeRsp/customriscv/cv32e40x/rtl/cv32e40x_core.sv
  D:/KachiCodeRsp/customriscv/cv32e40x/rtl/cv32e40x_cs_registers.sv
  D:/KachiCodeRsp/customriscv/cv32e40x/rtl/cv32e40x_csr.sv
  D:/KachiCodeRsp/customriscv/cv32e40x/rtl/cv32e40x_data_obi_interface.sv
  D:/KachiCodeRsp/customriscv/cv32e40x/rtl/cv32e40x_debug_triggers.sv
  D:/KachiCodeRsp/customriscv/cv32e40x/rtl/cv32e40x_decoder.sv
  D:/KachiCodeRsp/customriscv/cv32e40x/rtl/cv32e40x_div.sv
  D:/KachiCodeRsp/customriscv/cv32e40x/rtl/cv32e40x_ex_stage.sv
  D:/KachiCodeRsp/customriscv/cv32e40x/rtl/cv32e40x_ff_one.sv
  D:/KachiCodeRsp/customriscv/cv32e40x/rtl/cv32e40x_i_decoder.sv
  D:/KachiCodeRsp/customriscv/cv32e40x/rtl/cv32e40x_id_stage.sv
  D:/KachiCodeRsp/customriscv/cv32e40x/rtl/cv32e40x_if_c_obi.sv
  D:/KachiCodeRsp/customriscv/cv32e40x/rtl/cv32e40x_if_stage.sv
  D:/KachiCodeRsp/customriscv/cv32e40x/rtl/cv32e40x_if_xif.sv
  D:/KachiCodeRsp/customriscv/cv32e40x/rtl/cv32e40x_instr_obi_interface.sv
  D:/KachiCodeRsp/customriscv/cv32e40x/rtl/cv32e40x_int_controller.sv
  D:/KachiCodeRsp/customriscv/cv32e40x/rtl/cv32e40x_load_store_unit.sv
  D:/KachiCodeRsp/customriscv/cv32e40x/rtl/cv32e40x_lsu_response_filter.sv
  D:/KachiCodeRsp/customriscv/cv32e40x/rtl/cv32e40x_m_decoder.sv
  D:/KachiCodeRsp/customriscv/cv32e40x/rtl/cv32e40x_mpu.sv
  D:/KachiCodeRsp/customriscv/cv32e40x/rtl/cv32e40x_mult.sv
  D:/KachiCodeRsp/customriscv/cv32e40x/rtl/cv32e40x_pc_target.sv
  D:/KachiCodeRsp/customriscv/cv32e40x/rtl/cv32e40x_pma.sv
  D:/KachiCodeRsp/customriscv/cv32e40x/rtl/cv32e40x_prefetch_unit.sv
  D:/KachiCodeRsp/customriscv/cv32e40x/rtl/cv32e40x_prefetcher.sv
  D:/KachiCodeRsp/customriscv/cv32e40x/rtl/cv32e40x_register_file.sv
  D:/KachiCodeRsp/customriscv/cv32e40x/rtl/cv32e40x_register_file_wrapper.sv
  D:/KachiCodeRsp/customriscv/cv32e40x/rtl/cv32e40x_sequencer.sv
  D:/KachiCodeRsp/customriscv/cv32e40x/rtl/cv32e40x_sleep_unit.sv
  D:/KachiCodeRsp/customriscv/cv32e40x/rtl/cv32e40x_wb_stage.sv
  D:/KachiCodeRsp/customriscv/cv32e40x/rtl/cv32e40x_wpt.sv
  D:/KachiCodeRsp/customriscv/cv32e40x/rtl/cv32e40x_write_buffer.sv
  D:/KachiCodeRsp/customriscv/cv32e40x/rtl/cv32e40x_fpga_top.sv
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/KachiCodeRsp/customriscv/cv32e40x/constraints/cv32e40x_fpga_top.xdc
set_property used_in_implementation false [get_files D:/KachiCodeRsp/customriscv/cv32e40x/constraints/cv32e40x_fpga_top.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top cv32e40x_fpga_top -part xc7a35ticsg324-1L


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef cv32e40x_fpga_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file cv32e40x_fpga_top_utilization_synth.rpt -pb cv32e40x_fpga_top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
